// This file was generated by Mendix Studio Pro.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package kafka.actions;

import java.time.Duration;
import java.util.Arrays;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.Properties;
import org.apache.kafka.clients.consumer.ConsumerRecord;
import org.apache.kafka.clients.consumer.ConsumerRecords;
import org.apache.kafka.clients.consumer.KafkaConsumer;
import org.apache.kafka.common.TopicPartition;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import kafka.impl.KafkaModule;
import kafka.impl.KafkaPropertiesFactory;
import kafka.proxies.Header;
import kafka.proxies.Message;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class GetMessagesFromOffset extends CustomJavaAction<java.util.List<IMendixObject>>
{
	/** @deprecated use consumer.getMendixObject() instead. */
	@java.lang.Deprecated(forRemoval = true)
	private final IMendixObject __consumer;
	private final kafka.proxies.Consumer consumer;
	private final java.lang.String topic;
	private final java.lang.Long partition;
	private final java.lang.Long offset;
	private final java.lang.Long amount;

	public GetMessagesFromOffset(
		IContext context,
		IMendixObject _consumer,
		java.lang.String _topic,
		java.lang.Long _partition,
		java.lang.Long _offset,
		java.lang.Long _amount
	)
	{
		super(context);
		this.__consumer = _consumer;
		this.consumer = _consumer == null ? null : kafka.proxies.Consumer.initialize(getContext(), _consumer);
		this.topic = _topic;
		this.partition = _partition;
		this.offset = _offset;
		this.amount = _amount;
	}

	@java.lang.Override
	public java.util.List<IMendixObject> executeAction() throws Exception
	{
		// BEGIN USER CODE
		Properties kafkaProps = KafkaPropertiesFactory.getKafkaProperties(getContext(), consumer);
		kafkaProps.put("enable.auto.commit", "false");
		kafkaProps.put("max.poll.records", amount.intValue());
		kafkaProps.remove("group.id");
		
		KafkaConsumer<String, String> kafkaConsumer = new KafkaConsumer<>(kafkaProps);
		List<IMendixObject> result = new LinkedList<>();
		
		try {
			TopicPartition tp = new TopicPartition(topic, partition.intValue());
			kafkaConsumer.assign(Arrays.asList(tp));
			kafkaConsumer.seek(tp, offset);
			ConsumerRecords<String, String> records = kafkaConsumer.poll(Duration.ofMillis(5000));
			for (ConsumerRecord<String, String> record : records) {
				Message newMessage = new Message(getContext());
				newMessage.setOffset(record.offset());
				newMessage.setPartition(record.partition());
				newMessage.setTopic(record.topic());
				newMessage.setKey(record.key());
				newMessage.setPayload(record.value());
				newMessage.setTimestamp(new Date(record.timestamp()));
				result.add(newMessage.getMendixObject());
				
				for (org.apache.kafka.common.header.Header header : record.headers()) {
					Header headerObj = new Header(getContext());
					headerObj.setKey(header.key());
					headerObj.setValue(new String(header.value()));
					headerObj.setHeader_Message(newMessage);
				}
				
			}
		} catch (Exception e) {
			KafkaModule.LOGGER.error("Error while obtaining position for " + consumer.getName() + ": " + e.getMessage(), e);
			throw e;
		} finally {
			kafkaConsumer.close();
		}
		return result;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 * @return a string representation of this action
	 */
	@java.lang.Override
	public java.lang.String toString()
	{
		return "GetMessagesFromOffset";
	}

	// BEGIN EXTRA CODE
	// END EXTRA CODE
}
